# Generated by Django 5.1.4 on 2025-02-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('numberOfPages', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('text', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
    ]
